
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec: 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: cassandra:3.11.11
          ports:
            - containerPort: {{ .Values.network.port }}
      
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: eks.amazonaws.com/nodegroup 
               operator: In
               values:
                - large-nodes

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.network.port }}
  selector:
    app: {{ .Chart.Name }}
