namespace: knowlg-api

env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: muzafferjoya/content
image_tag: release-5.5.0_RC1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 9000
  targetport: 9000
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%
