### Default variable file for taxonomy-service ###

namespace: knowlg-api

env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: muzafferjoya/taxonomy-service
image_tag: release-5.2.0_RC3
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 9006
  targetport: 9000
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%




